### ISSUE TITLE
Add methods to set `weight`, `minsize`, `uniform` and `pad` on row object directly

### ISSUE THREAD

**Issue by rdbende** [insolor/tkinter_layout_helpers#11]
It would be useful to have methods (or maybe properties(?), although they wouldn't play nicely with the the current fluent interface) to set `weight`, `minsize`, `uniform` and `pad` on a row object directly. So you could do something like this:

```py
grid.new_row().add(tk.Label()).column_span(3).minsize(150).pad(10)
grid.new_row().skip(2).add(tk.Label()).column_span(4).weight(2).minsize(100)
```

instead of this:

```py
grid.new_row().add(tk.Label()).column_span(3)
grid.new_row().skip(2).add(tk.Label()).column_span(4)

grid.rowconfigure(0, minsize=150, pad=10)
grid.rowconfigure(3, weight=2, minsize=100)
```

So again it helps avoid manual calculation of row indices and makes the code much cleaner. The unfortunate thing would be that you still need to use the `{row|column}configure` methods to set the same stuff on columns.

This would help avoid manual calculation of row indices and makes the code much cleaner. The unfortunate thing is that you still have to use the `columnconfigure` method to set the same stuff on columns.

**Comment by insolor** [comment]
Actually, rows have [`.configure()`](https://github.com/insolor/tkinter_layout_helpers/blob/2856e3c5164e4f7e5c6e374e0647b13174f8568f/tkinter_layout_helpers/grid_helper.py#L59) method, and you can write code like this:
```
grid.new_row().add(tk.Label()).column_span(3).configure(minsize=150, pad=10)
grid.new_row().skip(2).add(tk.Label()).column_span(4).configure(weight=2, minsize=100)
```

**Comment by rdbende** [comment]
Yeah, I just noticed :D
